version: '3'

services:
  web:
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:3.14-alpine
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: jack_bot