version: "3.8"

services:
  web:
    image: node:14-alpine
    entrypoint: entrypoint/entrypoint.sh
    env_file: .env
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:3.14-alpine
    container_name: db
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: telegrammodbot_user
      POSTGRES_PASSWORD: b0yP1EP75Od6OyrF3vNQOxmzEcFnlV8I
      POSTGRES_DB: telegrammodbot
